class Autogenerated {
  String address;
  String dateOfBirth;
  String displayName;
  String email;
  String firstName;
  String id;
  String lastName;
  String nationality;
  String passportPhoto;
  String password;
  String placeOfBirth;
  String status;
  int telephoneNumber;

  Autogenerated(
      {this.address,
      this.dateOfBirth,
      this.displayName,
      this.email,
      this.firstName,
      this.id,
      this.lastName,
      this.nationality,
      this.passportPhoto,
      this.password,
      this.placeOfBirth,
      this.status,
      this.telephoneNumber});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    address = json['address'];
    dateOfBirth = json['dateOfBirth'];
    displayName = json['displayName'];
    email = json['email'];
    firstName = json['firstName'];
    id = json['id'];
    lastName = json['lastName'];
    nationality = json['nationality'];
    passportPhoto = json['passportPhoto'];
    password = json['password'];
    placeOfBirth = json['placeOfBirth'];
    status = json['status'];
    telephoneNumber = json['telephoneNumber'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['address'] = this.address;
    data['dateOfBirth'] = this.dateOfBirth;
    data['displayName'] = this.displayName;
    data['email'] = this.email;
    data['firstName'] = this.firstName;
    data['id'] = this.id;
    data['lastName'] = this.lastName;
    data['nationality'] = this.nationality;
    data['passportPhoto'] = this.passportPhoto;
    data['password'] = this.password;
    data['placeOfBirth'] = this.placeOfBirth;
    data['status'] = this.status;
    data['telephoneNumber'] = this.telephoneNumber;
    return data;
  }
}